version: '3.1'

services:
  db:
    image: postgres
    environment:
     POSTGRES_DB: "test_db"
     POSTGRES_USER: "postgres"
     POSTGRES_PASSWORD: "123"
     PGDATA: "D:/test"
    ports:
      - 5432:5432
    volumes:
      - ./src/main/java/org/example:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080